name: Zip Release Artifacts
description: Zip Release Artifacts

runs:
  using: 'composite'

  steps:
    - name: Zip Release artifacts - Linux
      if: runner.os == 'Linux'
      shell: bash
      run: cd ..
        && zip -r esmini/esmini-bin_ubuntu.zip esmini/bin esmini/EnvironmentSimulator/Applications/odrplot/xodr.py esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMLib.hpp esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMWrapper.cs esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMUnityUtil.cs esmini/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp esmini/EnvironmentSimulator/Libraries/esminiLib/ESMiniWrapper.cs esmini/version.txt

    - name: Zip Release artifacts - MacOS
      if: runner.os == 'macOS'
      shell: bash
      run: lipo -create bin/libesminiRMLib.dylib -output bin/esminiRMLib.bundle
        && lipo -create bin/libesminiLib.dylib -output bin/esminiLib.bundle
        && cd ..
        && zip -r esmini/esmini-bin_mac_catalina.zip esmini/bin esmini/EnvironmentSimulator/Applications/odrplot/xodr.py esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMLib.hpp esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMWrapper.cs esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMUnityUtil.cs esmini/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp esmini/EnvironmentSimulator/Libraries/esminiLib/ESMiniWrapper.cs esmini/version.txt

    - name: Zip Release artifacts - Windows
      if: runner.os == 'Windows'
      shell: bash
      run: cd ..
        && 7z a esmini/esmini-bin_win_x64.zip -r esmini/bin/ esmini/EnvironmentSimulator/Applications/odrplot/xodr.py esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMLib.hpp esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMWrapper.cs esmini/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMUnityUtil.cs esmini/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp esmini/EnvironmentSimulator/Libraries/esminiLib/ESMiniWrapper.cs esmini/version.txt
