name: Continuous Integration

on:
  push:
    branches:
    - master
    - dev

  pull_request:
    branches:
    - master
    - dev

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.8"
    - run: pip install -r support/python/requirements.txt

    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: jwlawson/actions-setup-cmake@v1.13.1

    - name: Setup VS Dev Environment - Windows
      if: matrix.os == 'windows-latest'
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: Install clang-tidy-17 - Ubuntu
      if: matrix.os == 'ubuntu-18.04'
      env:
        LLVM_URL: http://apt.llvm.org/bionic/
        LLVM_PKG: llvm-toolchain-bionic
      run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - 2>/dev/null
        && sudo add-apt-repository -y "deb ${{ env.LLVM_URL }} ${{ env.LLVM_PKG }} main"
        && sudo apt-get update -q
        && sudo apt-get install -y -q clang-tidy-17
        && sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-17 200

    - name: Build cppcheck 2.10 - Ubuntu
      if: matrix.os == 'ubuntu-18.04'
      env:
        CPPCHECK_BUILD: /home/cppcheck/build
        CPPCHECK_SRC: /home/cppcheck/cppcheck-src
      run: sudo apt-get purge --auto-remove cppcheck
        && sudo apt-get install -y -q libxml2-utils libz3-dev libtinyxml2-dev libpcre3-dev
        && sudo mkdir -p ${{ env.CPPCHECK_BUILD }}
        && git clone --branch 2.10 https://github.com/danmar/cppcheck.git ${{ env.CPPCHECK_SRC }}
        && cmake -S ${{ env.CPPCHECK_SRC }} -B ${{ env.CPPCHECK_BUILD }} -G "Ninja" -DCMAKE_BUILD_TYPE:STRING=Release -DHAVE_RULES=On -DBUILD_GUI=Off
        && cmake --build ${{ env.CPPCHECK_BUILD }} -j
        && sudo cmake --install ${{ env.CPPCHECK_BUILD }}

    - name: Output Ubuntu tools versions
      if: matrix.os == 'ubuntu-18.04'
      run: gcc --version
        && clang --version
        && gcc-7 --version
        && pip --version
        && ninja --version
        && cmake --version
        && clang-tidy --version
        && cppcheck --version

    - name: Output MacOS tools versions
      if: matrix.os == 'macos-latest'
      run: clang --version
        && pip --version
        && ninja --version
        && cmake --version

    - name: Output Windows tools versions
      if: matrix.os == 'macos-latest'
      run: cl
        && pip --version
        && ninja --version
        && cmake --version